// Generated by gencpp from file stereo_vo/relative_pose.msg
// DO NOT EDIT!


#ifndef STEREO_VO_MESSAGE_RELATIVE_POSE_H
#define STEREO_VO_MESSAGE_RELATIVE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace stereo_vo
{
template <class ContainerAllocator>
struct relative_pose_
{
  typedef relative_pose_<ContainerAllocator> Type;

  relative_pose_()
    : header()
    , key_stamp()
    , relative_pose()  {
    }
  relative_pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , key_stamp()
    , relative_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _key_stamp_type;
  _key_stamp_type key_stamp;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _relative_pose_type;
  _relative_pose_type relative_pose;





  typedef boost::shared_ptr< ::stereo_vo::relative_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stereo_vo::relative_pose_<ContainerAllocator> const> ConstPtr;

}; // struct relative_pose_

typedef ::stereo_vo::relative_pose_<std::allocator<void> > relative_pose;

typedef boost::shared_ptr< ::stereo_vo::relative_pose > relative_posePtr;
typedef boost::shared_ptr< ::stereo_vo::relative_pose const> relative_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stereo_vo::relative_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stereo_vo::relative_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stereo_vo::relative_pose_<ContainerAllocator1> & lhs, const ::stereo_vo::relative_pose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.key_stamp == rhs.key_stamp &&
    lhs.relative_pose == rhs.relative_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stereo_vo::relative_pose_<ContainerAllocator1> & lhs, const ::stereo_vo::relative_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stereo_vo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stereo_vo::relative_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stereo_vo::relative_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stereo_vo::relative_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stereo_vo::relative_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stereo_vo::relative_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stereo_vo::relative_pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stereo_vo::relative_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f31346257682659e34166a0fcbe1157";
  }

  static const char* value(const ::stereo_vo::relative_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f31346257682659ULL;
  static const uint64_t static_value2 = 0xe34166a0fcbe1157ULL;
};

template<class ContainerAllocator>
struct DataType< ::stereo_vo::relative_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stereo_vo/relative_pose";
  }

  static const char* value(const ::stereo_vo::relative_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stereo_vo::relative_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"time key_stamp\n"
"geometry_msgs/Pose relative_pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::stereo_vo::relative_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stereo_vo::relative_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.key_stamp);
      stream.next(m.relative_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct relative_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stereo_vo::relative_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stereo_vo::relative_pose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.key_stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "relative_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.relative_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEREO_VO_MESSAGE_RELATIVE_POSE_H
